### ISSUE TITLE
about ITP

### ISSUE THREAD

**Issue by rogers0** [kusm/fxlinuxprint-debian#1]
Dear Sasaki-san,

Sorry for writing in English. I don't have IME settled yet for my new PC.

I usually install this from fuji-xerox site, but today I want to install on amd64 for my new PC and don't want to enable multi-arch, so I googled and found this repo.

I find it useful, and I'm wondering why you didn't file ITP.
The license is GPL and debian/ folder seems well done.
If you don't have enough time, I can help. Thanks.

Cheers,
Roger

**Comment by uwabami** [comment]
使っていただきありがとうございます。

ITP していない一番の理由は、私にプリンタ周り(具体的にはCUPS周り)の知識が無いので継続的にメンテナンスできないから、です。

でも、ユーザがいるなら本家にuplandしても良いと思いましたので、近々 ITP します。

ではでは。

**Comment by rogers0** [comment]
承知しました。
ITPをお待ちしております。

ネットに関連記事・パッチ・BTSなどが少しあるので、連絡致します。
ITPの際に対応できなくても、今後に参考できると思います。

- https://da-cha.jp/?q=node/541
- http://debian.fam.cx/index.php?uploader#fxlinuxprint
- https://bugs.launchpad.net/ubuntu/+bug/124442

よろしく

**Comment by rogers0** [comment]
Stretch のフリーズ時期が近づいてますので、co-maintain しようと考えております。
今月に勝手に ITP / RFS をさせて頂きます。
よろしくお願いします。

**Comment by uwabami** [comment]
あ、はい。手がまわってませんので、ありがたいです。よろしくお願いいたします。
